# Generated by Django 5.2.7 on 2025-11-02 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "faculty_department",
                    models.CharField(
                        help_text="Enter your faculty or department. If none, type 'External'.",
                        max_length=150,
                    ),
                ),
                (
                    "mother_tongue",
                    models.CharField(
                        help_text="Enter your first/native language. If multilingual, list them separated by commas.",
                        max_length=100,
                    ),
                ),
                (
                    "university_status",
                    models.CharField(
                        choices=[
                            ("undergrad_first", "Undergraduate student (1st Year)"),
                            ("undergrad_other", "Undergraduate student (Other Years)"),
                            ("mphil", "MPhil student"),
                            ("phd_first", "PhD student (1st Year)"),
                            ("phd_other", "PhD student (Other Years)"),
                            ("postdoc", "Post-doctoral research"),
                            ("academic_staff", "Academic staff / Lecturer"),
                            ("support_staff", "Support staff"),
                            ("fee_paying", "Fee-paying member"),
                            ("academic_visitor", "Academic visitor"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Select your current university status.",
                        max_length=50,
                    ),
                ),
                (
                    "language_mandatory_name",
                    models.CharField(
                        help_text="Specify the main language you wish to learn or improve.",
                        max_length=100,
                    ),
                ),
                (
                    "language_mandatory_proficiency",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        help_text="Select your current proficiency level for this language.",
                        max_length=20,
                    ),
                ),
                (
                    "language_mandatory_goals",
                    models.JSONField(
                        help_text="List of learning/development goals selected for this language."
                    ),
                ),
                (
                    "language_optional_name",
                    models.CharField(
                        blank=True,
                        help_text="Specify an additional language you wish to learn or improve (optional).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "language_optional_proficiency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        help_text="Select your current proficiency level for this additional language.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "language_optional_goals",
                    models.JSONField(
                        blank=True,
                        help_text="List of learning/development goals selected for this additional language.",
                        null=True,
                    ),
                ),
                (
                    "aspects_to_improve",
                    models.TextField(
                        help_text="What specific aspects of the language(s) would you like to learn or improve?",
                        max_length=2000,
                    ),
                ),
                (
                    "activities_you_can_manage",
                    models.TextField(
                        help_text="List the activities you can manage in the language(s)",
                        max_length=2000,
                    ),
                ),
                (
                    "hours_per_week",
                    models.CharField(
                        help_text="Roughly how many hours per week will you devote to language learning?",
                        max_length=300,
                    ),
                ),
                (
                    "other_languages_studied",
                    models.TextField(
                        blank=True,
                        help_text="List any other languages you have previously studied (optional).",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "additional_comments",
                    models.TextField(
                        blank=True,
                        help_text="Any final comments you'd like to share with us (optional).",
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this questionnaire has been completed and submitted",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_profile",
                    models.ForeignKey(
                        help_text="The student profile this questionnaire belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaires",
                        to="profiles.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questionnaire",
                "verbose_name_plural": "Questionnaires",
                "ordering": ["-created_at"],
            },
        ),
    ]
