# Generated by Django 5.2.7 on 2025-11-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaire",
            name="university_status",
            field=models.CharField(
                choices=[
                    ("undergrad_first", "Undergraduate student (1st Year)"),
                    ("undergrad_other", "Undergraduate student (Other Years)"),
                    ("mphil", "MPhil student"),
                    ("phd_first", "PhD student (1st Year)"),
                    ("phd_other", "PhD student (Other Years)"),
                    ("postdoc", "Post-doctoral research"),
                    ("academic_staff", "Academic staff / Lecturer"),
                    ("support_staff", "Support staff"),
                    ("fee_paying", "Fee-paying member"),
                    ("academic_visitor", "Academic visitor"),
                    ("other", "Other"),
                ],
                help_text="Select your current university status.",
                max_length=50,
            ),
        ),
    ]
