# Generated by Django 5.2.7 on 2025-11-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="studentnote",
            new_name="notes_stude_student_43b846_idx",
            old_name="notes_note_student_6dd17b_idx",
        ),
    ]
