# Generated by Django 5.2.7 on 2025-11-02 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("in_person", "In-person"),
                            ("both", "Both (Online + In-person)"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Availabilities",
                "ordering": ["date", "start_time"],
                "indexes": [
                    models.Index(fields=["teacher", "date"], name="availabilit_teacher_baa40e_idx")
                ],
                "unique_together": {("teacher", "date", "start_time")},
            },
        ),
    ]
