# Generated by Django 5.2.7 on 2025-11-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("availability", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="availability",
            name="message",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional short message or note for this time slot (max 200 characters)",
                max_length=200,
            ),
        ),
    ]
