# Generated by Django 5.2.7 on 2025-11-04 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("availability", "0002_availability_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, default="", help_text="Optional message from student to teacher"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "availability",
                    models.OneToOneField(
                        help_text="The availability slot being booked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="availability.availability",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["availability__date", "availability__start_time"],
                "indexes": [
                    models.Index(
                        fields=["student", "availability"], name="availabilit_student_0c9eab_idx"
                    )
                ],
            },
        ),
    ]
