# Generated by Django 5.2.7 on 2025-02-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("availability", "0003_booking"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="Booking",
                ),
            ],
        ),
    ]
