# Generated by Django 5.2.7 on 2025-02-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("availability", "0004_move_booking_to_booking_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availability",
            name="message",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional short message or note for this time slot (max 600 characters)",
                max_length=600,
            ),
        ),
    ]
